services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
      - "5173:5173"
    environment:
      VITE_PORT: 5173

  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ./:/var/www/html
    command: ["php-fpm", "-F"]

  nginx:
    image: nginx:alpine
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app
