services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    user: "1000:1000"
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
    environment:
      APP_URL: http://localhost:8080
    depends_on:
      - mysql

  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    user: "1000:1000"
    volumes:
      - ./:/var/www/html
    entrypoint: []
    command: ["php-fpm", "-F"]
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_app
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_PORT: ${DB_PORT}
    depends_on:
      - mysql

volumes:
  mysql_data: