version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_app
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: laravel
            PMA_PASSWORD: laravel
            PMA_PORT: 3306
        depends_on:
            - mysql

volumes:
    mysql_data:
