[entryPoints.web]
  address = ":80"

[entryPoints.websecure]
  address = ":443"

[api]
  dashboard = true

[providers.docker]
  exposedByDefault = false

[providers.file]
  filename = "/etc/traefik/dynamic.toml"
  watch = true

[certificatesResolvers.letsencrypt.acme]
  email = "example@leasoft.org"
  storage = "/etc/traefik/acme.json"
  [certificatesResolvers.letsencrypt.acme.tlsChallenge]
